import { describe, expect, test } from "bun:test";

import {
	extraMarkdownLinksGuard,
	mdxSpacingGuard,
	sentenceCaseHeadingsGuard,
} from "@/app/services/translator/validation/guards/advisory-style.guard";

describe("sentenceCaseHeadingsGuard", () => {
	test("flags Title Case on common Portuguese words", () => {
		const source = "## New Features\n\nBody.";
		const translated = "## Novos Recursos do React\n\nCorpo.";

		expect(sentenceCaseHeadingsGuard(source, translated)?.guardId).toBe("sentenceCaseHeadings");
	});

	test("returns null when proper nouns stay capitalized", () => {
		const source = "## React Compiler\n\nBody.";
		const translated = "## React Compiler\n\nCorpo.";

		expect(sentenceCaseHeadingsGuard(source, translated)).toBeNull();
	});

	test("returns null for sentence-case Portuguese headings", () => {
		const source = "## New features\n\nBody.";
		const translated = "## Novos recursos do React\n\nCorpo.";

		expect(sentenceCaseHeadingsGuard(source, translated)).toBeNull();
	});
});

describe("mdxSpacingGuard", () => {
	test("flags prose glued to slug comments", () => {
		const source = "## Title {/*slug*/}\n\npor [Name](url).";
		const translated = "## Título{/*slug*/}\n\npor[Name](url).";

		expect(mdxSpacingGuard(source, translated)?.guardId).toBe("mdxSpacing");
	});

	test("returns null when slug and link spacing is preserved", () => {
		const source = "## Title {/*slug*/}\n\npor [Name](url).";
		const translated = "## Título {/*slug*/}\n\npor [Name](url).";

		expect(mdxSpacingGuard(source, translated)).toBeNull();
	});

	test("returns null for nested backticks inside markdown link labels", () => {
		const translated =
			"`hydrateRoot` lets you display React components previously generated by [`react-dom/server`.](/reference/react-dom/server)";

		expect(mdxSpacingGuard("x", translated)).toBeNull();
	});

	test("flags inline code glued to following prose", () => {
		const translated = "Use `hydrateRoot`to attach React.";

		expect(mdxSpacingGuard("x", translated)?.guardId).toBe("mdxSpacing");
	});

	test("flags missing space between adjacent markdown link closers", () => {
		const translated = "[A](url1)],[B](url2)";

		expect(mdxSpacingGuard("x", translated)?.guardId).toBe("mdxSpacing");
	});
});

describe("extraMarkdownLinksGuard", () => {
	test("flags links added during translation", () => {
		const source = "- [Website](https://example.com)";
		const translated =
			"- [Website](https://example.com)\n- [Programação](https://example.com/schedule)";

		expect(extraMarkdownLinksGuard(source, translated)?.guardId).toBe("extraMarkdownLinks");
	});

	test("returns null when only link labels change", () => {
		const source = "- [Website](https://example.com)";
		const translated = "- [Site](https://example.com)";

		expect(extraMarkdownLinksGuard(source, translated)).toBeNull();
	});
});
