import { describe, expect, test } from "bun:test";

import { findExtraMarkdownLinks } from "@/app/services/translator/validation/analyzers/advisory-style.analyzer";
import {
	englishServerClientTermsGuard,
	extraMarkdownLinksGuard,
	mdxSpacingGuard,
	sentenceCaseHeadingsGuard,
} from "@/app/services/translator/validation/guards/advisory-style.guard";

describe("sentenceCaseHeadingsGuard", () => {
	test("flags Title Case on common Portuguese words", () => {
		const source = "## New Features\n\nBody.";
		const translated = "## Novos Recursos do React\n\nCorpo.";

		expect(sentenceCaseHeadingsGuard(source, translated)?.guardId).toBe("sentenceCaseHeadings");
	});

	test("returns null when proper nouns stay capitalized", () => {
		const source = "## React Compiler\n\nBody.";
		const translated = "## React Compiler\n\nCorpo.";

		expect(sentenceCaseHeadingsGuard(source, translated)).toBeNull();
	});

	test("returns null for sentence-case Portuguese headings", () => {
		const source = "## New features\n\nBody.";
		const translated = "## Novos recursos do React\n\nCorpo.";

		expect(sentenceCaseHeadingsGuard(source, translated)).toBeNull();
	});
});

describe("mdxSpacingGuard", () => {
	test("flags prose glued to slug comments", () => {
		const source = "## Title {/*slug*/}\n\npor [Name](url).";
		const translated = "## Título{/*slug*/}\n\npor [Name](url).";

		expect(mdxSpacingGuard(source, translated)?.guardId).toBe("mdxSpacing");
	});

	test("returns null when slug and link spacing is preserved", () => {
		const source = "## Title {/*slug*/}\n\npor [Name](url).";
		const translated = "## Título {/*slug*/}\n\npor [Name](url).";

		expect(mdxSpacingGuard(source, translated)).toBeNull();
	});

	test("returns null for nested backticks inside markdown link labels", () => {
		const translated =
			"`hydrateRoot` lets you display React components previously generated by [`react-dom/server`.](/reference/react-dom/server)";

		expect(mdxSpacingGuard("x", translated)).toBeNull();
	});

	test("flags inline code glued to following prose", () => {
		const translated = "Use `hydrateRoot`to attach React.";

		expect(mdxSpacingGuard("x", translated)?.guardId).toBe("mdxSpacing");
	});

	test("flags missing space between adjacent markdown link closers", () => {
		const translated = "[A](url1)],[B](url2)";

		expect(mdxSpacingGuard("x", translated)?.guardId).toBe("mdxSpacing");
	});

	test("flags Portuguese word glued to markdown link (advisory only — not auto-repaired)", () => {
		const translated = "por[Link](url)";

		expect(mdxSpacingGuard("x", translated)?.guardId).toBe("mdxSpacing");
	});

	test("flags inline code glued to non-ASCII prose letter", () => {
		const translated = "ver `useState`é obrigatório.";

		expect(mdxSpacingGuard("x", translated)?.guardId).toBe("mdxSpacing");
	});

	test("returns null for properly spaced inline code before prose", () => {
		const translated = "Use `hydrateRoot` to attach React.";

		expect(mdxSpacingGuard("x", translated)).toBeNull();
	});

	test("includes violation label and excerpt in guard message", () => {
		const translated = "Use `hydrateRoot`to attach React.";
		const result = mdxSpacingGuard("x", translated);

		expect(result?.message).toContain("MDX spacing issues detected");
		expect(result?.message).toContain("missing space after inline code");
	});
});

describe("extraMarkdownLinksGuard", () => {
	test("flags links added during translation", () => {
		const source = "- [Website](https://example.com)";
		const translated =
			"- [Website](https://example.com)\n- [Programação](https://example.com/schedule)";

		expect(extraMarkdownLinksGuard(source, translated)?.guardId).toBe("extraMarkdownLinks");
	});

	test("returns null when only link labels change", () => {
		const source = "- [Website](https://example.com)";
		const translated = "- [Site](https://example.com)";

		expect(extraMarkdownLinksGuard(source, translated)).toBeNull();
	});

	test("returns null when MDN docs URLs are rewritten to the target locale", () => {
		const source = "[string](https://developer.mozilla.org/en-US/docs/Glossary/String)";
		const translated = "[string](https://developer.mozilla.org/ru/docs/Glossary/String)";

		expect(findExtraMarkdownLinks(source, translated)).toEqual([]);
		expect(extraMarkdownLinksGuard(source, translated)).toBeNull();
	});
});

describe("englishServerClientTermsGuard", () => {
	test("flags English Server/Client Component terms in prose", () => {
		const translated = "импортируется из Server Component и считаются Client Components.";

		expect(englishServerClientTermsGuard("x", translated)?.guardId).toBe(
			"englishServerClientTerms",
		);
	});

	test("returns null when product terms are localized", () => {
		const translated =
			"импортируется из серверного компонента и считаются клиентскими компонентами.";

		expect(englishServerClientTermsGuard("x", translated)).toBeNull();
	});

	test("ignores English terms inside inline code", () => {
		const translated = "используйте `Server Component` в коде, но серверный компонент в prose.";

		expect(englishServerClientTermsGuard("x", translated)).toBeNull();
	});

	test("ignores English terms inside fenced code blocks", () => {
		const translated = "```js\nconst Server Component = 1;\n```\nТекст.";

		expect(englishServerClientTermsGuard("x", translated)).toBeNull();
	});
});
