import type {
	ProcessedFileResult,
	PullRequestStatus,
	ReviewerValidationNotice,
} from "@/app/services/github/types";
import type { TranslationFile } from "@/app/services/translator/";
import type { PostTranslationGuardId } from "@/app/services/translator/validation/validation.constants";

export type { ReviewerValidationNotice };

/** Prior invalid PR for the same file path */
export interface InvalidFilePullRequest {
	prNumber: number;
	status: PullRequestStatus;
}

/** Inputs for locale-specific pull request body templates */
export interface PullRequestDescriptionMetadata {
	languageName: string;
	invalidFilePR: InvalidFilePullRequest | undefined;

	/** Advisory post-translation guard hints for maintainers (empty if clean) */
	reviewerNotices: readonly ReviewerValidationNotice[];
}

/** Inputs for a pull request comment after maintainer-feedback remediation */
export interface RemediationPullRequestCommentParams {
	/** Basename of the translated markdown file */
	readonly filename: string;

	/** Maintainer logins whose unresolved reviews triggered remediation */
	readonly maintainerLogins: readonly string[];

	/** Workflow run metadata when executing in GitHub Actions */
	readonly runContext?: ProgressCommentRunContext;

	/** Count of advisory post-translation guard notices on the refreshed PR body */
	readonly advisoryNoticeCount: number;
}

/**
 * GitHub Actions metadata for the translation-progress issue comment opener.
 */
export interface ProgressCommentRunContext {
	/** Package version from `package.json` */
	readonly version: string;

	/** Absolute URL to the matching GitHub release tag for {@link ProgressCommentRunContext.version} */
	readonly releaseUrl: string;

	/** Workflow display name from the workflow file `name` field */
	readonly workflowName: string;

	/** Numeric workflow run id */
	readonly runId: string;

	/** Absolute URL to the workflow run */
	readonly url: string;
}

/**
 * Configuration for GitHub issue/PR comments in the target language.
 *
 * Contains locale-specific text templates for automated PR creation and
 * issue tracking comments generated by the translation workflow.
 */
export interface LocaleCommentConfig {
	/**
	 * Opening line of the translation-progress issue comment for this workflow run.
	 *
	 * @param runContext Actions run metadata when available; omitted outside CI
	 *
	 * @returns Localized comment opener
	 */
	readonly prefix: (runContext?: ProgressCommentRunContext) => string;

	/** Section heading when new pull requests were opened in this run */
	readonly createdSectionHeader: string;

	/** Section heading when existing pull requests received new translation commits */
	readonly updatedSectionHeader: string;

	/** Generates the footer/observations section of the comment */
	readonly suffix: string;

	/**
	 * Comment posted on an open pull request when a remediation commit is pushed.
	 *
	 * @param params File name, maintainer logins, optional run metadata, and advisory notice count
	 *
	 * @returns Localized pull request comment body
	 */
	readonly remediationPullRequestComment: (params: RemediationPullRequestCommentParams) => string;
}

/**
 * Language-specific translation rules for the LLM.
 *
 * Contains instructions that guide the translation model on
 * language-specific conventions, terminology, and exceptions.
 */
export interface LocaleRulesConfig {
	/**
	 * Specific translation instructions appended to the system prompt.
	 *
	 * These rules override or supplement generic translation guidelines
	 * with language-specific requirements (e.g., term translations,
	 * URL locale adjustments, style conventions).
	 */
	readonly specific: string;

	/**
	 * Optional override for the markdown "What to Translate" scope section.
	 *
	 * When set, replaces the default scope bullets in document prompts.
	 */
	readonly markdownTranslationScopeSection?: string;
}

/**
 * Locale-specific strings for building PR body content.
 *
 * Contains all translatable text used in the PR description template,
 * enabling a single shared builder to generate locale-specific PR bodies.
 */
export interface LocalePRBodyStrings {
	/** Human-review notice as the opening body paragraph */
	readonly humanReviewNotice: string;

	/** Conflict notice section when a stale PR was closed */
	readonly conflictNotice: {
		/** Bold title text (e.g., "Previous PR closed") */
		readonly title: string;

		/**
		 * Body explaining why the PR was closed.
		 *
		 * @param prNumber The closed PR number
		 *
		 * @returns Formatted conflict notice
		 */
		readonly body: (prNumber: number) => string;
	};

	/**
	 * Maintainer wiki link for the `[!TIP]` callout below the human-review notice.
	 *
	 * @param wikiUrl Absolute URL to the For React Docs Maintainers wiki page
	 *
	 * @returns Formatted `[!TIP]` body text
	 */
	readonly maintainerWikiTip: (wikiUrl: string) => string;

	/** Advisory validation warnings (shown only when `reviewerNotices` is non-empty) */
	readonly reviewerWarnings: {
		/** Intro line inside the `[!WARNING]` callout */
		readonly intro: string;

		/** `<summary>` label for the collapsible validation details block */
		readonly detailsSummary: string;

		/**
		 * Human-readable heading for an advisory guard id in the details section.
		 *
		 * @param guardId Post-translation guard identifier
		 *
		 * @returns Localized validator name
		 */
		readonly guardLabel: (guardId: PostTranslationGuardId) => string;

		/**
		 * Localized violation count for a guard subsection heading.
		 *
		 * @param count Number of located violations in the section
		 *
		 * @returns Phrase such as `1 violação` or `3 violations`
		 */
		readonly violationTally: (count: number) => string;
	};
}

export interface LocalePullRequestConfig {
	/**
	 * Title template for the pull request in the target language.
	 *
	 * @param file The translation file being processed
	 *
	 * @returns Formatted PR title string
	 */
	readonly title: (file: TranslationFile) => string;

	/**
	 * Body template builder for the pull request in the target language.
	 *
	 * @param file The translation file being processed
	 * @param processingResult The result of processing the file
	 * @param metadata Metadata about the pull request description
	 *
	 * @returns Formatted PR body string
	 */
	readonly body: (
		file: TranslationFile,
		processingResult: ProcessedFileResult,
		metadata: PullRequestDescriptionMetadata,
	) => string;
}

/**
 * Complete locale definition for a target translation language.
 *
 * Defines all user-facing and LLM-facing text content that varies
 * by target language in the translation workflow.
 *
 * @example
 * ```typescript
 * const ptBr: LocaleDefinition = {
 *   comment: {
 *     prefix: (runContext) => runContext ? "A última execução..." : "As seguintes páginas...",
 *     suffix: "> [!IMPORTANT]\n> ...",
 *   },
 *   rules: {
 *     specific: "# PORTUGUESE (BRAZIL) SPECIFIC RULES\n...",
 *   },
 *   pullRequest: {
 *     title: (file) => `Translation of ${file.filename}`,
 *     body: createPRBodyBuilder(ptBrStrings),
 *   },
 * };
 * ```
 */
export interface LocaleDefinition {
	/** GitHub comment templates in the target language */
	readonly comment: LocaleCommentConfig;

	/** LLM translation rules specific to this language */
	readonly rules: LocaleRulesConfig;

	/** Pull request templates in the target language */
	readonly pullRequest: LocalePullRequestConfig;
}
