import type {
	ProcessedFileResult,
	PullRequestDescriptionMetadata,
	TranslationFile,
} from "@/services";

/**
 * Configuration for GitHub issue/PR comments in the target language.
 *
 * Contains locale-specific text templates for automated PR creation and
 * issue tracking comments generated by the translation workflow.
 */
export interface LocaleCommentConfig {
	/** Opening line of the PR comment summarizing translated pages */
	readonly prefix: string;

	/** Generates the footer/observations section of the comment */
	readonly suffix: string;
}

/**
 * Language-specific translation rules for the LLM.
 *
 * Contains instructions that guide the translation model on
 * language-specific conventions, terminology, and exceptions.
 */
export interface LocaleRulesConfig {
	/**
	 * Specific translation instructions appended to the system prompt.
	 *
	 * These rules override or supplement generic translation guidelines
	 * with language-specific requirements (e.g., term translations,
	 * URL locale adjustments, style conventions).
	 */
	readonly specific: string;
}

/**
 * Locale-specific strings for building PR body content.
 *
 * Contains all translatable text used in the PR description template,
 * enabling a single shared builder to generate locale-specific PR bodies.
 */
export interface LocalePRBodyStrings {
	/**
	 * Introductory sentence for the PR body.
	 *
	 * @param languageName The display name of the target language
	 *
	 * @returns Formatted intro string
	 */
	readonly intro: (languageName: string) => string;

	/** Conflict notice section when a stale PR was closed */
	readonly conflictNotice: {
		/** Bold title text (e.g., "Previous PR closed") */
		readonly title: string;

		/**
		 * Body explaining why the PR was closed.
		 *
		 * @param prNumber The closed PR number
		 * @param mergeableState The mergeable state that caused closure
		 *
		 * @returns Formatted conflict explanation
		 */
		readonly body: (prNumber: number, mergeableState: string) => string;

		/** Explanation of the complete rewrite approach */
		readonly rewriteExplanation: string;
	};

	/** Important notice about human review requirement */
	readonly humanReviewNotice: string;

	/** Text for the collapsible details summary */
	readonly detailsSummary: string;

	/** Processing statistics section */
	readonly stats: {
		/** Section header text */
		readonly header: string;

		/** Table column headers and row labels */
		readonly metrics: {
			readonly metricColumn: string;
			readonly valueColumn: string;
			readonly sourceSize: string;
			readonly translationSize: string;
			readonly contentRatio: string;
			readonly filePath: string;
			readonly processingTime: string;
		};

		/** Explanatory notes below the stats table */
		readonly notes: readonly string[];
	};

	/** Technical information section */
	readonly techInfo: {
		/** Section header text */
		readonly header: string;

		/** Label for generation date */
		readonly generationDate: string;

		/** Label for branch name */
		readonly branch: string;
	};

	/** BCP 47 locale string for time formatting (e.g., "pt-BR", "ru-RU") */
	readonly timeFormatLocale: string;
}

export interface LocalePullRequestConfig {
	/**
	 * Title template for the pull request in the target language.
	 *
	 * @param file The translation file being processed
	 *
	 * @returns Formatted PR title string
	 */
	readonly title: (file: TranslationFile) => string;

	/**
	 * Body template builder for the pull request in the target language.
	 *
	 * @param file The translation file being processed
	 * @param processingResult The result of processing the file
	 * @param metadata Metadata about the pull request description
	 *
	 * @returns Formatted PR body string
	 */
	readonly body: (
		file: TranslationFile,
		processingResult: ProcessedFileResult,
		metadata: PullRequestDescriptionMetadata,
	) => string;
}

/**
 * Complete locale definition for a target translation language.
 *
 * Defines all user-facing and LLM-facing text content that varies
 * by target language in the translation workflow.
 *
 * @example
 * ```typescript
 * const ptBr: LocaleDefinition = {
 *   comment: {
 *     prefix: "As seguintes páginas foram traduzidas...",
 *     suffix: "> [!IMPORTANT]\n> ...",
 *   },
 *   rules: {
 *     specific: "# PORTUGUESE (BRAZIL) SPECIFIC RULES\n...",
 *   },
 *   pullRequest: {
 *     title: (file) => `Translation of ${file.filename}`,
 *     body: createPRBodyBuilder(ptBrStrings),
 *   },
 * };
 * ```
 */
export interface LocaleDefinition {
	/** GitHub comment templates in the target language */
	readonly comment: LocaleCommentConfig;

	/** LLM translation rules specific to this language */
	readonly rules: LocaleRulesConfig;

	/** Pull request templates in the target language */
	readonly pullRequest: LocalePullRequestConfig;
}
