/**
 * Configuration for GitHub issue/PR comments in the target language.
 *
 * Contains locale-specific text templates for automated PR creation and
 * issue tracking comments generated by the translation workflow.
 */
export interface LocaleCommentConfig {
	/** Opening line of the PR comment summarizing translated pages */
	prefix: string;

	/**
	 * Generates the footer/observations section of the comment.
	 *
	 * @param repoForkOwner Owner of the fork repository to link back to the source workflow
	 *
	 * @returns Formatted observations section with locale-specific content
	 */
	suffix: (repoForkOwner: string) => string;
}

/**
 * Language-specific translation rules for the LLM.
 *
 * Contains instructions that guide the translation model on
 * language-specific conventions, terminology, and exceptions.
 */
export interface LocaleRulesConfig {
	/**
	 * Specific translation instructions appended to the system prompt.
	 *
	 * These rules override or supplement generic translation guidelines
	 * with language-specific requirements (e.g., term translations,
	 * URL locale adjustments, style conventions).
	 */
	specific: string;
}

/**
 * Complete locale definition for a target translation language.
 *
 * Defines all user-facing and LLM-facing text content that varies
 * by target language in the translation workflow.
 *
 * @example
 * ```typescript
 * const ptBr: LocaleDefinition = {
 *   comment: {
 *     prefix: "As seguintes páginas foram traduzidas...",
 *     suffix: (owner) => `###### Observações\n- ...`,
 *   },
 *   rules: {
 *     specific: "# PORTUGUESE (BRAZIL) SPECIFIC RULES\n...",
 *   },
 * };
 * ```
 */
export interface LocaleDefinition {
	/** GitHub comment templates in the target language */
	comment: LocaleCommentConfig;

	/** LLM translation rules specific to this language */
	rules: LocaleRulesConfig;
}
